# Generated by Django 5.2.4 on 2025-08-04 19:58

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat('first_name', models.Value(' '), 'last_name'), output_field=models.CharField(max_length=201))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat('first_name', models.Value(' '), 'last_name'), output_field=models.CharField(max_length=201))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('air_date', models.DateField()),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('genre', models.CharField(choices=[('ACTION', 'Action'), ('ADVENTURE', 'Adventure'), ('ANIMATION', 'Animation'), ('COMEDY', 'Comedy'), ('CRIME', 'Crime'), ('DOCUMENTARY', 'Documentary'), ('DRAMA', 'Drama'), ('FAMILY', 'Family'), ('FANTASY', 'Fantasy'), ('HISTORY', 'History'), ('HORROR', 'Horror'), ('KIDS', 'Kids'), ('MYSTERY', 'Mystery'), ('NEWS', 'News'), ('REALITY', 'Reality'), ('ROMANCE', 'Romance'), ('SCI_FI', 'Sci-Fi'), ('SOAP', 'Soap'), ('TALK', 'Talk Show'), ('THRILLER', 'Thriller'), ('WAR', 'War'), ('WESTERN', 'Western')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('poster', models.ImageField(upload_to='posters/movies/')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('episode_number', models.PositiveSmallIntegerField()),
                ('air_date', models.DateField()),
                ('description', models.TextField()),
                ('duration', models.DurationField()),
                ('actors', models.ManyToManyField(related_name='tv_show_episodes', to='movies.actor')),
                ('directors', models.ManyToManyField(related_name='tv_show_episodes', to='movies.director')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movies.season')),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movies.episode')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('genre', models.CharField(choices=[('ACTION', 'Action'), ('ADVENTURE', 'Adventure'), ('ANIMATION', 'Animation'), ('COMEDY', 'Comedy'), ('CRIME', 'Crime'), ('DOCUMENTARY', 'Documentary'), ('DRAMA', 'Drama'), ('FAMILY', 'Family'), ('FANTASY', 'Fantasy'), ('HISTORY', 'History'), ('HORROR', 'Horror'), ('KIDS', 'Kids'), ('MYSTERY', 'Mystery'), ('NEWS', 'News'), ('REALITY', 'Reality'), ('ROMANCE', 'Romance'), ('SCI_FI', 'Sci-Fi'), ('SOAP', 'Soap'), ('TALK', 'Talk Show'), ('THRILLER', 'Thriller'), ('WAR', 'War'), ('WESTERN', 'Western')], max_length=20)),
                ('release_date', models.DateField()),
                ('duration', models.DurationField()),
                ('poster', models.ImageField(upload_to='posters/movies/')),
                ('actors', models.ManyToManyField(related_name='movies', to='movies.actor')),
                ('directors', models.ManyToManyField(related_name='movies', to='movies.director')),
            ],
        ),
        migrations.CreateModel(
            name='MovieRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movies.movie')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='movies.tvshow'),
        ),
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(fields=('season', 'episode_number'), name='unique_episode_number_per_season'),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('show', 'number')},
        ),
    ]
